//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GANCursProject681
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ANDBEntities : DbContext
    {
        public ANDBEntities()
            : base("name=ANDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consumable> Consumable { get; set; }
        public virtual DbSet<DeliveryOfConsumables> DeliveryOfConsumables { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<StatusOfConsumableIssued> StatusOfConsumableIssued { get; set; }
        public virtual DbSet<StatusOfWorker> StatusOfWorker { get; set; }
        public virtual DbSet<SuplierStatus> SuplierStatus { get; set; }
        public virtual DbSet<SuppliesInDelivery> SuppliesInDelivery { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TheSupplier> TheSupplier { get; set; }
        public virtual DbSet<TypeOfConsumable> TypeOfConsumable { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
