//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GANCursProject681
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consumable()
        {
            this.DeliveryOfConsumables = new HashSet<DeliveryOfConsumables>();
            this.SuppliesInDelivery = new HashSet<SuppliesInDelivery>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int FK_TypeOfConsumable_id { get; set; }
        public int FK_Unit_id { get; set; }
        public int InventoryNumber { get; set; }
    
        public virtual TypeOfConsumable TypeOfConsumable { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryOfConsumables> DeliveryOfConsumables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliesInDelivery> SuppliesInDelivery { get; set; }
    }
}
