//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GANCursProject681
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryOfConsumables
    {
        public int id { get; set; }
        public int FK_Consumable_id { get; set; }
        public int FK_Worker_id { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public int Quantity { get; set; }
        public int FK_StatusOfConsumableIssued_id { get; set; }
    
        public virtual Consumable Consumable { get; set; }
        public virtual StatusOfConsumableIssued StatusOfConsumableIssued { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
