//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GANCursProject681
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supply()
        {
            this.SuppliesInDelivery = new HashSet<SuppliesInDelivery>();
        }
    
        public int id { get; set; }
        public int FK_WarehouseNumber_id { get; set; }
        public int FK_TheSuplier_id { get; set; }
        public System.DateTime DateOfIssue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuppliesInDelivery> SuppliesInDelivery { get; set; }
        public virtual TheSupplier TheSupplier { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
