//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GANCursProject681
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliesInDelivery
    {
        public int id { get; set; }
        public int FK_Supply_id { get; set; }
        public int FK_Consumable_id { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> DateOfManufacture { get; set; }
    
        public virtual Consumable Consumable { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
