//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GANCursProject681
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheSupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheSupplier()
        {
            this.Supply = new HashSet<Supply>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string TheContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public string LegalAddress { get; set; }
        public string Email { get; set; }
        public Nullable<int> FK_SuplierStatus_id { get; set; }
    
        public virtual SuplierStatus SuplierStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply> Supply { get; set; }
    }
}
